package tk.zielony.gravity.game;

public enum AchievementType {
	LOW_APM, PLAY_ZOOMED_OUT, PLAY_ZOOMED_IN, DESTROY_SPACESHIP, GOOD_GAME, CREATE_EARTH, CREATE_SUN, SLOW_JAVA, HIGH_APM, UPSIDE_DOWN, CREATE_SATURN, CREATE_MARS
}